import type { Env } from '../../types';
import { json } from '../../http/responses';
export async function creatorApi(request:Request,env:Env,guildId:string):Promise<Response>{
 if(request.method==='GET'){const rows=await env.DB.prepare('SELECT * FROM creator_sources WHERE guild_id=? ORDER BY created_at DESC').bind(guildId).all();return json({sources:rows.results});}
 if(request.method==='POST'){const b=await request.json<any>();if(!['rss','youtube','twitch'].includes(b.source_type)||!b.label||!b.source_value||!b.discord_channel_id)return json({error:'invalid_source'},400);const now=Date.now();
  if(b.id){await env.DB.prepare(`UPDATE creator_sources SET source_type=?,label=?,source_value=?,discord_channel_id=?,mention_role_id=?,live_message=?,offline_message=?,notify_live=?,notify_offline=?,vod_url=?,cooldown_minutes=?,enabled=?,updated_at=? WHERE id=? AND guild_id=?`).bind(b.source_type,String(b.label),String(b.source_value),String(b.discord_channel_id),b.mention_role_id||null,b.live_message||null,b.offline_message||null,b.notify_live===false?0:1,b.notify_offline?1:0,b.vod_url||null,Math.max(1,Number(b.cooldown_minutes||10)),b.enabled===false?0:1,now,Number(b.id),guildId).run();return json({ok:true});}
  const r=await env.DB.prepare(`INSERT INTO creator_sources(guild_id,source_type,label,source_value,discord_channel_id,mention_role_id,live_message,offline_message,notify_live,notify_offline,vod_url,cooldown_minutes,enabled,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,1,?,?)`).bind(guildId,b.source_type,String(b.label),String(b.source_value),String(b.discord_channel_id),b.mention_role_id||null,b.live_message||null,b.offline_message||null,b.notify_live===false?0:1,b.notify_offline?1:0,b.vod_url||null,Math.max(1,Number(b.cooldown_minutes||10)),now,now).run();return json({ok:true,id:Number(r.meta.last_row_id)});}
 if(request.method==='DELETE'){const id=Number(new URL(request.url).searchParams.get('id'));await env.DB.prepare('DELETE FROM creator_sources WHERE id=? AND guild_id=?').bind(id,guildId).run();return json({ok:true});}return json({error:'method_not_allowed'},405);
}
