import type { Env } from '../../types';
import { discord } from '../../discord/client';
type External={live:boolean,id:string,title:string,url:string,vodUrl?:string};
export async function pollCreatorSources(env:Env):Promise<void>{
 const sources=(await env.DB.prepare('SELECT * FROM creator_sources WHERE enabled=1 ORDER BY COALESCE(last_checked_at,0) ASC LIMIT 50').all<any>()).results;
 for(const s of sources){try{const item=s.source_type==='twitch'?await twitchState(env,s.source_value):s.source_type==='youtube'?await youtubeState(env,s.source_value):await rssState(s.source_value);const now=Date.now();await env.DB.prepare('UPDATE creator_sources SET last_checked_at=?,last_error=NULL WHERE id=?').bind(now,s.id).run();if(!item)continue;
   const wasLive=!!s.last_live_state, isLive=item.live, cooldown=Number(s.cooldown_minutes||10)*60000, canNotify=!s.last_notified_at||now-Number(s.last_notified_at)>=cooldown;
   if(s.source_type==='rss'){if(!s.last_external_id){await env.DB.prepare('UPDATE creator_sources SET last_external_id=? WHERE id=?').bind(item.id,s.id).run();continue;}if(item.id!==s.last_external_id&&canNotify){await sendAlert(env,s,render(s.live_message||'{creator} posted something new!\n{title}\n{url}',s,item));await env.DB.prepare('UPDATE creator_sources SET last_external_id=?,last_notified_at=? WHERE id=?').bind(item.id,now,s.id).run();}continue;}
   if(isLive&&!wasLive&&s.notify_live&&canNotify){await sendAlert(env,s,render(s.live_message||'🔴 **{creator} is LIVE!**\n{title}\n{url}',s,item));await env.DB.prepare('UPDATE creator_sources SET last_live_state=1,last_external_id=?,last_notified_at=? WHERE id=?').bind(item.id,now,s.id).run();continue;}
   if(!isLive&&wasLive){if(s.notify_offline&&canNotify)await sendAlert(env,s,render(s.offline_message||'💜 **{creator} has finished streaming.**\nCatch up here: {vod_url}',s,item));await env.DB.prepare('UPDATE creator_sources SET last_live_state=0,last_notified_at=? WHERE id=?').bind(s.notify_offline?now:s.last_notified_at,s.id).run();continue;}
   await env.DB.prepare('UPDATE creator_sources SET last_live_state=?,last_external_id=? WHERE id=?').bind(isLive?1:0,item.id||s.last_external_id,s.id).run();
  }catch(e){await env.DB.prepare('UPDATE creator_sources SET last_checked_at=?,last_error=? WHERE id=?').bind(Date.now(),String(e).slice(0,300),s.id).run();}}
}
async function sendAlert(env:Env,s:any,content:string){const mention=s.mention_role_id?`<@&${s.mention_role_id}> `:'';await discord(env,`/channels/${s.discord_channel_id}/messages`,{method:'POST',body:JSON.stringify({content:`${mention}${content}`.slice(0,2000),allowed_mentions:{roles:s.mention_role_id?[s.mention_role_id]:[]}})});}
function render(t:string,s:any,i:External){return t.replaceAll('{creator}',s.label).replaceAll('{title}',i.title||'').replaceAll('{url}',i.url||'').replaceAll('{vod_url}',s.vod_url||i.vodUrl||i.url||'');}
async function twitchState(env:Env,login:string):Promise<External>{if(!env.TWITCH_CLIENT_ID||!env.TWITCH_CLIENT_SECRET)throw new Error('twitch_secrets_missing');const tokenRes=await fetch(`https://id.twitch.tv/oauth2/token?client_id=${encodeURIComponent(env.TWITCH_CLIENT_ID)}&client_secret=${encodeURIComponent(env.TWITCH_CLIENT_SECRET)}&grant_type=client_credentials`,{method:'POST'});if(!tokenRes.ok)throw new Error('twitch_token');const token=await tokenRes.json<any>();const r=await fetch(`https://api.twitch.tv/helix/streams?user_login=${encodeURIComponent(login)}`,{headers:{'client-id':env.TWITCH_CLIENT_ID,authorization:`Bearer ${token.access_token}`}});if(!r.ok)throw new Error(`twitch_${r.status}`);const x=(await r.json<any>()).data?.[0];return x?{live:true,id:x.id,title:x.title||`${login} is live`,url:`https://twitch.tv/${login}`,vodUrl:`https://twitch.tv/${login}/videos`}:{live:false,id:`offline:${login}`,title:'Offline',url:`https://twitch.tv/${login}`,vodUrl:`https://twitch.tv/${login}/videos`};}
async function youtubeState(env:Env,channelId:string):Promise<External>{if(env.YOUTUBE_API_KEY){const u=new URL('https://www.googleapis.com/youtube/v3/search');u.searchParams.set('part','snippet');u.searchParams.set('channelId',channelId);u.searchParams.set('eventType','live');u.searchParams.set('type','video');u.searchParams.set('maxResults','1');u.searchParams.set('key',env.YOUTUBE_API_KEY);const r=await fetch(u);if(!r.ok)throw new Error(`youtube_${r.status}`);const x=(await r.json<any>()).items?.[0];if(x)return {live:true,id:x.id.videoId,title:x.snippet?.title||'Live on YouTube',url:`https://youtube.com/watch?v=${x.id.videoId}`,vodUrl:`https://youtube.com/channel/${channelId}/streams`};return {live:false,id:`offline:${channelId}`,title:'Offline',url:`https://youtube.com/channel/${channelId}`,vodUrl:`https://youtube.com/channel/${channelId}/streams`};}const latest=await feedLatest(`https://www.youtube.com/feeds/videos.xml?channel_id=${encodeURIComponent(channelId)}`);return latest?{live:false,id:latest.id,title:latest.title,url:latest.url,vodUrl:`https://youtube.com/channel/${channelId}/streams`}:{live:false,id:`offline:${channelId}`,title:'Offline',url:`https://youtube.com/channel/${channelId}`,vodUrl:`https://youtube.com/channel/${channelId}/streams`};}
async function rssState(url:string):Promise<External|null>{const x=await feedLatest(url);return x?{live:false,...x}:null;}
async function feedLatest(url:string){const r=await fetch(url,{headers:{'user-agent':'OrbitBot/0.1 creator notifier'}});if(!r.ok)throw new Error(`feed_${r.status}`);const xml=await r.text();const block=match(xml,/<item\b[\s\S]*?<\/item>/i)||match(xml,/<entry\b[\s\S]*?<\/entry>/i);if(!block)return null;const title=decode(tag(block,'title')||'New post');const id=decode(tag(block,'guid')||tag(block,'id')||attr(block,'link','href')||tag(block,'link')||title);const urlOut=decode(attr(block,'link','href')||tag(block,'link')||'');return {id,title,url:urlOut};}
function match(s:string,r:RegExp){return s.match(r)?.[0]||''}function tag(s:string,n:string){return s.match(new RegExp(`<${n}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${n}>`,'i'))?.[1]?.replace(/<!\[CDATA\[|\]\]>/g,'').trim()||''}function attr(s:string,n:string,a:string){return s.match(new RegExp(`<${n}[^>]*\\s${a}=["']([^"']+)["'][^>]*>`,'i'))?.[1]||''}function decode(s:string){return s.replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;/g,"'")}
