export const moduleCatalog = [
  { id: 'moderation', label: 'Moderation', status: 'active', description: 'AutoMod, warnings, temporary actions, honeypot and moderation history.' },
  { id: 'roles', label: 'Roles', status: 'active', description: 'Reaction, button, select-menu, automatic and temporary role systems.' },
  { id: 'verification', label: 'Verification', status: 'active', description: 'Rules + Turnstile verification and combined access roles.' },
  { id: 'tickets', label: 'Tickets', status: 'active', description: 'Dropdown categories, forms, routing, claiming and transcripts.' },
  { id: 'leveling', label: 'Leveling', status: 'active', description: 'XP, ranks, rewards, exclusions and leaderboards.' },
  { id: 'automation', label: 'Automation', status: 'active', description: 'Trigger, condition and action workflows.' },
  { id: 'scheduler', label: 'Scheduled Posts', status: 'active', description: 'Batch queue, recurring posts, templates and delivery history.' },
  { id: 'kofi', label: 'Ko-fi', status: 'active', description: 'Milestones, webhook events and Discord announcements.' },
  { id: 'social', label: 'Social Publishing', status: 'active', description: 'Discord, Bluesky, Mastodon and Threads publishing plus queued short-form video delivery are active.' },
  { id: 'creator', label: 'Creator Notifications', status: 'active', description: 'Owner-only Twitch My Stream alerts plus community RSS, YouTube, Twitch, podcast and TikTok notifications into Discord.' },
  { id: 'diagnostics', label: 'Diagnostics', status: 'active', description: 'Configuration, permission and infrastructure health checks.' },
  { id: 'community', label: 'Community', status: 'active', description: 'Welcome/goodbye, auto-role, custom commands, polls, reminders and sticky messages.' },
  { id: 'community-engagement', label: 'Community Engagement', status: 'active', description: 'Recurring question prompts with uploadable question banks and duplicate prevention.' },
  { id: 'security', label: 'Security Center', status: 'active', description: 'Permission risk scanning and reversible selected-channel incident lockdown.' },
  { id: 'channel-manager', label: 'Owner Channel Manager', status: 'active', description: 'Owner-only bulk channel creation, dependency-aware deletion, structural backups and restore.' },
] as const;
