import type { Env } from '../../types';
import { discord } from '../../discord/client';
import { json } from '../../http/responses';
import { audit } from '../../repositories/audit';
const ADMIN=1n<<3n, MANAGE_CHANNELS=1n<<4n, MANAGE_GUILD=1n<<5n, BAN=1n<<2n, MANAGE_ROLES=1n<<28n, MANAGE_WEBHOOKS=1n<<29n, SEND=1n<<11n;
export async function securityApi(request:Request,env:Env,guildId:string,actorId:string):Promise<Response>{
 if(request.method==='GET'){const [config,scan]=await Promise.all([env.DB.prepare('SELECT * FROM security_configs WHERE guild_id=?').bind(guildId).first<any>(),scanGuild(env,guildId)]);return json({config:config??{},...scan});}
 if(request.method==='POST'){const b=await request.json<any>();const now=Date.now();if(b.op==='save'){await env.DB.prepare(`INSERT INTO security_configs(guild_id,lockdown_active,lockdown_channel_ids_json,alert_channel_id,updated_by,updated_at) VALUES(?,0,?,?,?,?) ON CONFLICT(guild_id) DO UPDATE SET lockdown_channel_ids_json=excluded.lockdown_channel_ids_json,alert_channel_id=excluded.alert_channel_id,updated_by=excluded.updated_by,updated_at=excluded.updated_at`).bind(guildId,JSON.stringify(Array.isArray(b.channel_ids)?b.channel_ids:[]),b.alert_channel_id||null,actorId,now).run();return json({ok:true});}
 if(b.op==='lockdown_on'){if(b.confirm!=='LOCKDOWN')return json({error:'confirmation_required'},400);const cfg=await env.DB.prepare('SELECT * FROM security_configs WHERE guild_id=?').bind(guildId).first<any>();const channels=parse(cfg?.lockdown_channel_ids_json,[]);for(const id of channels){const r=await discord(env,`/channels/${id}`);if(!r.ok)continue;const ch=await r.json<any>();await env.DB.prepare('INSERT OR REPLACE INTO lockdown_channel_snapshots(guild_id,channel_id,permission_overwrites_json,captured_at) VALUES(?,?,?,?)').bind(guildId,id,JSON.stringify(ch.permission_overwrites||[]),now).run();const overwrites=[...(ch.permission_overwrites||[])];const idx=overwrites.findIndex((x:any)=>x.id===guildId&&x.type===0);if(idx>=0){const x=overwrites[idx];x.deny=(BigInt(x.deny||'0')|SEND).toString();x.allow=(BigInt(x.allow||'0')&~SEND).toString();}else overwrites.push({id:guildId,type:0,allow:'0',deny:SEND.toString()});await discord(env,`/channels/${id}`,{method:'PATCH',body:JSON.stringify({permission_overwrites:overwrites})});}await env.DB.prepare(`INSERT INTO security_configs(guild_id,lockdown_active,lockdown_channel_ids_json,updated_by,updated_at) VALUES(?,1,?,?,?) ON CONFLICT(guild_id) DO UPDATE SET lockdown_active=1,updated_by=excluded.updated_by,updated_at=excluded.updated_at`).bind(guildId,JSON.stringify(channels),actorId,now).run();await audit(env,guildId,actorId,'security_lockdown_enabled',{channels});return json({ok:true});}
 if(b.op==='lockdown_off'){if(b.confirm!=='RESTORE')return json({error:'confirmation_required'},400);const rows=(await env.DB.prepare('SELECT * FROM lockdown_channel_snapshots WHERE guild_id=?').bind(guildId).all<any>()).results;for(const row of rows)await discord(env,`/channels/${row.channel_id}`,{method:'PATCH',body:JSON.stringify({permission_overwrites:parse(row.permission_overwrites_json,[])})});await env.DB.prepare('DELETE FROM lockdown_channel_snapshots WHERE guild_id=?').bind(guildId).run();await env.DB.prepare('UPDATE security_configs SET lockdown_active=0,updated_by=?,updated_at=? WHERE guild_id=?').bind(actorId,now,guildId).run();await audit(env,guildId,actorId,'security_lockdown_disabled',{});return json({ok:true});}}
 return json({error:'method_not_allowed'},405);
}
async function scanGuild(env:Env,guildId:string){const r=await discord(env,`/guilds/${guildId}/roles`);if(!r.ok)return {score:0,findings:[{severity:'critical',title:'Could not inspect server roles',detail:`Discord returned ${r.status}`} ]};const roles=await r.json<any[]>();const findings:any[]=[];const everyone=roles.find(x=>x.id===guildId);if(everyone){const p=BigInt(everyone.permissions||'0');for(const [bit,title] of [[ADMIN,'@everyone has Administrator'],[MANAGE_CHANNELS,'@everyone can manage channels'],[MANAGE_GUILD,'@everyone can manage the server'],[BAN,'@everyone can ban members'],[MANAGE_ROLES,'@everyone can manage roles'],[MANAGE_WEBHOOKS,'@everyone can manage webhooks']] as const)if((p&bit)!==0n)findings.push({severity:'critical',title,detail:'Remove this permission from @everyone unless there is an exceptional reason.'});}for(const role of roles){const p=BigInt(role.permissions||'0');if(role.id!==guildId&&(p&ADMIN)!==0n)findings.push({severity:'warning',title:`${role.name} has Administrator`,detail:'Administrator bypasses channel-level restrictions. Prefer specific permissions where possible.'});}const penalty=findings.reduce((n,x)=>n+(x.severity==='critical'?20:7),0);return {score:Math.max(0,100-penalty),findings};}
function parse(raw:any,fallback:any){try{return typeof raw==='string'?JSON.parse(raw):raw??fallback}catch{return fallback}}
