import type { Env } from '../../types';
import { discord } from '../../discord/client';
import { audit } from '../../repositories/audit';
import { sha256 } from '../../security/crypto';
const SEND=1n<<11n;
const parse=(raw:any,f:any)=>{try{return typeof raw==='string'?JSON.parse(raw):raw??f}catch{return f}};
export async function activateShield(env:Env,guildId:string,actorId:string,reason:string){
 const cfg=await env.DB.prepare('SELECT * FROM shield_configs WHERE guild_id=?').bind(guildId).first<any>(); if(!cfg||!cfg.enabled||cfg.active)return false;
 const ids=parse(cfg.channel_ids_json,[]); const now=Date.now();
 for(const id of ids){const r=await discord(env,`/channels/${id}`);if(!r.ok)continue;const ch=await r.json<any>();await env.DB.prepare('INSERT OR REPLACE INTO shield_channel_snapshots(guild_id,channel_id,permission_overwrites_json,rate_limit_per_user,captured_at) VALUES(?,?,?,?,?)').bind(guildId,id,JSON.stringify(ch.permission_overwrites||[]),ch.rate_limit_per_user||0,now).run();const ow=[...(ch.permission_overwrites||[])];const i=ow.findIndex((x:any)=>x.id===guildId&&x.type===0);if(i>=0){ow[i].deny=(BigInt(ow[i].deny||'0')|SEND).toString();ow[i].allow=(BigInt(ow[i].allow||'0')&~SEND).toString();}else ow.push({id:guildId,type:0,allow:'0',deny:SEND.toString()});await discord(env,`/channels/${id}`,{method:'PATCH',body:JSON.stringify({permission_overwrites:ow,rate_limit_per_user:Math.max(Number(ch.rate_limit_per_user||0),Number(cfg.slowmode_seconds||30))})});}
 await env.DB.prepare('UPDATE shield_configs SET active=1,activated_at=?,activated_reason=?,updated_by=?,updated_at=? WHERE guild_id=?').bind(now,reason,actorId,now,guildId).run();
 if(cfg.alert_channel_id)await discord(env,`/channels/${cfg.alert_channel_id}/messages`,{method:'POST',body:JSON.stringify({content:`${cfg.alert_role_id?`<@&${cfg.alert_role_id}> `:''}🛡️ **Orbit Shield Mode activated**\nReason: ${reason}`})});
 await audit(env,guildId,actorId,'shield_activated',{reason,channels:ids}); return true;
}
export async function restoreShield(env:Env,guildId:string,actorId:string){const rows=(await env.DB.prepare('SELECT * FROM shield_channel_snapshots WHERE guild_id=?').bind(guildId).all<any>()).results;for(const row of rows)await discord(env,`/channels/${row.channel_id}`,{method:'PATCH',body:JSON.stringify({permission_overwrites:parse(row.permission_overwrites_json,[]),rate_limit_per_user:row.rate_limit_per_user||0})});await env.DB.prepare('DELETE FROM shield_channel_snapshots WHERE guild_id=?').bind(guildId).run();await env.DB.prepare('UPDATE shield_configs SET active=0,activated_at=NULL,activated_reason=NULL,updated_by=?,updated_at=? WHERE guild_id=?').bind(actorId,Date.now(),guildId).run();await audit(env,guildId,actorId,'shield_restored',{});}
export async function shieldMemberJoin(env:Env,data:any){const guildId=data.guild_id;if(!guildId)return;const cfg=await env.DB.prepare('SELECT * FROM shield_configs WHERE guild_id=?').bind(guildId).first<any>();if(!cfg?.enabled||!cfg.auto_activate||cfg.active)return;const now=Date.now();await env.DB.prepare("INSERT INTO shield_events(guild_id,event_type,actor_id,created_at) VALUES(?,'join',?,?)").bind(guildId,data.user?.id||null,now).run();const since=now-Number(cfg.join_window_seconds||30)*1000;const c=await env.DB.prepare("SELECT COUNT(*) c FROM shield_events WHERE guild_id=? AND event_type='join' AND created_at>=?").bind(guildId,since).first<any>();if(Number(c?.c||0)>=Number(cfg.join_threshold||15))await activateShield(env,guildId,'orbit:auto','Join spike detected');}
export async function shieldMessage(env:Env,data:any){const guildId=data.guild_id;if(!guildId||data.author?.bot)return;const cfg=await env.DB.prepare('SELECT * FROM shield_configs WHERE guild_id=?').bind(guildId).first<any>();if(!cfg?.enabled||!cfg.auto_activate||cfg.active)return;const now=Date.now();const mentions=(data.mentions?.length||0)+(data.mention_roles?.length||0);if(mentions>=Number(cfg.mention_threshold||8)){await activateShield(env,guildId,'orbit:auto','Mention spam detected');return;}const normalized=String(data.content||'').trim().toLowerCase().replace(/\s+/g,' ');if(normalized.length<4)return;const fp=await sha256(normalized);await env.DB.prepare("INSERT INTO shield_events(guild_id,event_type,actor_id,fingerprint,created_at) VALUES(?,'message',?,?,?)").bind(guildId,data.author?.id||null,fp,now).run();const c=await env.DB.prepare("SELECT COUNT(DISTINCT actor_id) c FROM shield_events WHERE guild_id=? AND event_type='message' AND fingerprint=? AND created_at>=?").bind(guildId,fp,now-30000).first<any>();if(Number(c?.c||0)>=Number(cfg.duplicate_threshold||6))await activateShield(env,guildId,'orbit:auto','Coordinated duplicate spam detected');}
