import type { Env } from '../../types';
import { addRole, removeRole, discord } from '../../discord/client';
import { audit } from '../../repositories/audit';
export async function runAutomations(env:Env,guildId:string,triggerType:string,ctx:any):Promise<void>{
 const sec=await env.DB.prepare('SELECT lockdown_active FROM security_configs WHERE guild_id=?').bind(guildId).first<any>();if(sec?.lockdown_active)return;
 const rows=(await env.DB.prepare('SELECT * FROM automations WHERE guild_id=? AND enabled=1').bind(guildId).all<any>()).results;for(const row of rows){const trigger=parse(row.trigger_json,{});if(trigger.type!==triggerType)continue;const conditions=parse(row.conditions_json,[]);if(!conditions.every((c:any)=>matches(c,ctx)))continue;const actions=parse(row.actions_json,[]);let ok=true;const results:any[]=[];for(const action of actions.slice(0,10)){try{results.push(await execute(env,guildId,action,ctx));}catch(e){ok=false;results.push({error:String(e)});}}await env.DB.prepare('INSERT INTO automation_runs(automation_id,guild_id,trigger_type,status,detail_json,ran_at) VALUES(?,?,?,?,?,?)').bind(row.id,guildId,triggerType,ok?'success':'partial',JSON.stringify(results),Date.now()).run();await audit(env,guildId,ctx.user_id||null,'automation_run',{automation_id:row.id,trigger_type:triggerType,status:ok?'success':'partial'});}
}
function matches(c:any,ctx:any){if(c.type==='channel_is')return ctx.channel_id===c.channel_id;if(c.type==='user_is')return ctx.user_id===c.user_id;if(c.type==='has_role')return (ctx.role_ids||[]).includes(c.role_id);return true;}
async function execute(env:Env,guildId:string,a:any,ctx:any){if(a.type==='send_message'){const channel=a.channel_id||ctx.channel_id;if(!channel)return {skipped:'no_channel'};const r=await discord(env,`/channels/${channel}/messages`,{method:'POST',body:JSON.stringify({content:String(a.content||'').slice(0,2000)})});return {type:a.type,status:r.status};}if(a.type==='add_role'){const r=await addRole(env,guildId,a.user_id||ctx.user_id,a.role_id);return {type:a.type,status:r.status};}if(a.type==='remove_role'){const r=await removeRole(env,guildId,a.user_id||ctx.user_id,a.role_id);return {type:a.type,status:r.status};}if(a.type==='ban'){const r=await discord(env,`/guilds/${guildId}/bans/${a.user_id||ctx.user_id}`,{method:'PUT',body:JSON.stringify({delete_message_seconds:0})});return {type:a.type,status:r.status};}return {skipped:'unknown_action'};}
function parse(raw:any,fallback:any){try{return typeof raw==='string'?JSON.parse(raw):raw??fallback}catch{return fallback}}
