import type { Env } from '../../types';
import { discord } from '../../discord/client';
import { loadGuildResources, validateChannelIds, validateRoleIds } from '../../discord/guild-resources';
import { json } from '../../http/responses';
export async function communityApi(request:Request,env:Env,guildId:string,actorId:string):Promise<Response>{
 if(request.method==='GET'){const [config,commands,stickies]=await Promise.all([env.DB.prepare('SELECT * FROM community_configs WHERE guild_id=?').bind(guildId).first(),env.DB.prepare('SELECT * FROM custom_commands WHERE guild_id=? ORDER BY command').bind(guildId).all(),env.DB.prepare('SELECT * FROM sticky_configs WHERE guild_id=?').bind(guildId).all()]);return json({config:config??{},commands:commands.results,stickies:stickies.results});}
 if(request.method==='POST'){const body=await request.json<any>();const op=body.op||'config';const now=Date.now();
  if(op==='config'){const resources=await loadGuildResources(env,guildId,{channels:true,roles:Boolean(body.autorole_id)});if(!resources.ok)return json(resources,resources.status);const invalidChannel=validateChannelIds(resources,[body.welcome_channel_id,body.goodbye_channel_id].filter(Boolean));if(invalidChannel)return json(invalidChannel,invalidChannel.status);const invalidRole=validateRoleIds(resources,[body.autorole_id].filter(Boolean),{assignable:true});if(invalidRole)return json(invalidRole,invalidRole.status);await env.DB.prepare(`INSERT INTO community_configs(guild_id,welcome_channel_id,welcome_message,goodbye_channel_id,goodbye_message,autorole_id,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(guild_id) DO UPDATE SET welcome_channel_id=excluded.welcome_channel_id,welcome_message=excluded.welcome_message,goodbye_channel_id=excluded.goodbye_channel_id,goodbye_message=excluded.goodbye_message,autorole_id=excluded.autorole_id,updated_at=excluded.updated_at`).bind(guildId,body.welcome_channel_id||null,body.welcome_message||null,body.goodbye_channel_id||null,body.goodbye_message||null,body.autorole_id||null,now).run();return json({ok:true});}
  if(op==='command'){const cmd=String(body.command||'').trim().replace(/^!/,'').toLowerCase();if(!/^[a-z0-9_-]{1,32}$/.test(cmd)||!body.response)return json({error:'invalid_command'},400);await env.DB.prepare(`INSERT INTO custom_commands(guild_id,command,response,enabled,created_at) VALUES(?,?,?,?,?) ON CONFLICT(guild_id,command) DO UPDATE SET response=excluded.response,enabled=1`).bind(guildId,cmd,String(body.response).slice(0,2000),1,now).run();return json({ok:true});}
  if(op==='sticky'||op==='poll'||op==='reminder'){if(!body.channel_id)return json({error:'invalid_channel'},400);const resources=await loadGuildResources(env,guildId,{channels:true});if(!resources.ok)return json(resources,resources.status);const invalid=validateChannelIds(resources,[body.channel_id]);if(invalid)return json(invalid,invalid.status);}
  if(op==='sticky'){if(!body.content)return json({error:'invalid_sticky'},400);await env.DB.prepare(`INSERT INTO sticky_configs(guild_id,channel_id,content,every_n_messages,enabled) VALUES(?,?,?,?,1) ON CONFLICT(guild_id,channel_id) DO UPDATE SET content=excluded.content,every_n_messages=excluded.every_n_messages,enabled=1`).bind(guildId,String(body.channel_id),String(body.content).slice(0,2000),Math.max(2,Number(body.every_n_messages||10))).run();return json({ok:true});}
  if(op==='poll'){const options=(body.options||[]).map((x:any)=>String(x)).filter(Boolean).slice(0,10);if(!body.question||options.length<2)return json({error:'invalid_poll'},400);const res=await discord(env,`/channels/${body.channel_id}/messages`,{method:'POST',body:JSON.stringify({poll:{question:{text:String(body.question).slice(0,300)},answers:options.map((x:string)=>({poll_media:{text:x}})),duration:Math.min(168,Math.max(1,Number(body.duration_hours||24))),allow_multiselect:Boolean(body.multiselect)},allowed_mentions:{parse:[]}})});return json({ok:res.ok},res.ok?200:400);}
  if(op==='reminder'){if(!body.content||!body.scheduled_for)return json({error:'invalid_reminder'},400);await env.DB.prepare('INSERT INTO scheduled_posts(guild_id,channel_id,content_json,timezone,scheduled_for,status,created_by,created_at,updated_at,paused,name) VALUES(?,?,?,?,?,?,?,?,?,?,?)').bind(guildId,String(body.channel_id),JSON.stringify({content:String(body.content)}),String(body.timezone||'UTC'),Number(body.scheduled_for),'queued',actorId,now,now,0,'Reminder').run();return json({ok:true});}
 }
 return json({error:'method_not_allowed'},405);
}
